import Link from "next/link";

export const metadata = {
  title: "Training - Basics | ICS Maugeri Tele-Neurophysiology Network",
  description: "A concise EEG training module on postsynaptic potentials, dipoles, polarity and scalp detection.",
};

const traceRows = [
  { label: "Fp1-F7", tone: "M 0 28 C 32 18, 42 43, 70 29 S 108 20, 134 30 S 168 40, 194 26 S 232 18, 260 30" },
  { label: "F7-T3", tone: "M 0 30 C 24 30, 34 18, 54 29 S 86 42, 112 28 S 150 18, 172 31 S 216 45, 260 26" },
  { label: "C3-P3", tone: "M 0 27 C 28 40, 48 20, 76 28 S 126 34, 148 27 S 170 18, 188 28 S 224 39, 260 29" },
  { label: "P3-O1", tone: "M 0 29 C 38 22, 54 37, 84 28 S 126 18, 154 31 S 190 42, 216 28 S 240 20, 260 30" },
];

const principles = [
  {
    title: "EEG is population activity",
    text: "Scalp EEG reflects synchronized postsynaptic fields generated by large groups of cortical neurons, not single-neuron action potentials.",
  },
  {
    title: "Geometry matters",
    text: "Pyramidal neurons align in columns. This open-field arrangement lets small extracellular currents add instead of cancel.",
  },
  {
    title: "The skull filters the signal",
    text: "By the time activity reaches the scalp, it has been attenuated and spatially blurred by tissue, skull and scalp.",
  },
];

const polarityRows = [
  ["Superficial excitation", "Relative negative sink", "Upgoing deflection"],
  ["Superficial inhibition", "Relative positive source", "Downgoing deflection"],
  ["Clinical display rule", "Negative values", "Displayed upward"],
];

export default function TrainingBasicsPage() {
  return (
    <main className="min-h-screen bg-[#F7FAFA] text-[#18282D]">
      <section className="relative overflow-hidden px-5 py-6 md:px-10">
        <div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.92fr_1.08fr] lg:items-center">
          <div>
            <Link href="/" className="text-[10px] uppercase tracking-[0.28em] text-[#2F6672]">
              ICS Maugeri Network
            </Link>
            <p className="mt-20 text-[10px] uppercase tracking-[0.36em] text-[#5E858C]">
              EEG Training
            </p>
            <h1 className="mt-5 max-w-4xl font-serif text-[4.5rem] leading-[0.88] tracking-normal text-[#17272C] md:text-[8rem]">
              Training - Basics
            </h1>
            <p className="mt-8 max-w-2xl text-xl font-light leading-[1.75] text-[#52686E] md:text-2xl">
              A first clinical module on how scalp EEG transforms synchronized cortical activity into the waveform seen on screen.
            </p>
          </div>

          <div className="border border-[#D7E4E6] bg-white/70 p-5 shadow-[0_24px_80px_rgba(24,40,45,0.08)] backdrop-blur">
            <div className="flex items-center justify-between border-b border-[#D7E4E6] pb-4">
              <p className="text-[10px] uppercase tracking-[0.26em] text-[#5E858C]">Live trace concept</p>
              <p className="font-serif text-4xl text-[#2F6672]">01</p>
            </div>
            <div className="mt-6 space-y-5">
              {traceRows.map((row) => (
                <div key={row.label} className="grid grid-cols-[4.75rem_1fr] items-center gap-4">
                  <span className="text-[10px] uppercase tracking-[0.2em] text-[#6E8589]">{row.label}</span>
                  <svg viewBox="0 0 260 58" className="h-12 w-full overflow-visible">
                    <path d="M0 29 H260" stroke="#D7E4E6" strokeWidth="1" />
                    <path d={row.tone} fill="none" stroke="#2F6672" strokeLinecap="round" strokeWidth="2" />
                  </svg>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="px-5 py-20 md:px-10">
        <div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-3">
          {principles.map((item, index) => (
            <article key={item.title} className="border-t border-[#BFD3D6] pt-6">
              <p className="font-serif text-5xl text-[#2F6672]">0{index + 1}</p>
              <h2 className="mt-8 text-xl font-medium text-[#17272C]">{item.title}</h2>
              <p className="mt-4 text-base leading-8 text-[#52686E]">{item.text}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="bg-white px-5 py-20 md:px-10">
        <div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.86fr_1.14fr]">
          <div>
            <p className="text-[10px] uppercase tracking-[0.34em] text-[#5E858C]">Physiology</p>
            <h2 className="mt-5 font-serif text-5xl leading-tight md:text-7xl">
              From cortical current to clinical waveform.
            </h2>
          </div>
          <div className="space-y-8 text-lg font-light leading-9 text-[#52686E]">
            <p>
              The major visible contribution to scalp EEG comes from postsynaptic potentials in cortical pyramidal neurons. Their aligned dendrites create a dipole: one region becomes relatively negative, another relatively positive.
            </p>
            <p>
              Action potentials are brief and poorly suited to scalp summation. Postsynaptic potentials last longer, allowing many small events to overlap into a field that can be measured at the scalp.
            </p>
          </div>
        </div>

        <div className="mx-auto mt-14 max-w-7xl overflow-hidden border border-[#D7E4E6]">
          <div className="grid bg-[#F3F7F7] text-[10px] uppercase tracking-[0.22em] text-[#5E858C] md:grid-cols-3">
            <div className="border-b border-[#D7E4E6] p-4 md:border-b-0 md:border-r">Event</div>
            <div className="border-b border-[#D7E4E6] p-4 md:border-b-0 md:border-r">Surface field</div>
            <div className="p-4">Clinical display</div>
          </div>
          {polarityRows.map((row) => (
            <div key={row[0]} className="grid border-t border-[#D7E4E6] text-sm text-[#2B3B40] md:grid-cols-3">
              {row.map((cell) => (
                <div key={cell} className="border-[#D7E4E6] p-4 leading-7 md:border-r md:last:border-r-0">
                  {cell}
                </div>
              ))}
            </div>
          ))}
        </div>
      </section>

      <section className="px-5 py-20 md:px-10">
        <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.1fr_0.9fr] lg:items-center">
          <div className="relative min-h-[28rem] border border-[#D7E4E6] bg-white">
            <div className="absolute left-1/2 top-1/2 h-72 w-52 -translate-x-1/2 -translate-y-1/2 rounded-[50%] border border-[#9ABBC0] bg-[#F7FAFA]" />
            <div className="absolute left-[52%] top-[18%] h-28 w-px rotate-[-18deg] bg-[#2F6672]" />
            <div className="absolute left-[54%] top-[17%] size-3 rounded-full bg-[#2F6672]" />
            <div className="absolute left-[47%] top-[46%] h-36 w-px rotate-[54deg] bg-[#88B7A5]" />
            <div className="absolute left-[44%] top-[64%] size-3 rounded-full bg-[#88B7A5]" />
            <p className="absolute left-6 top-6 text-[10px] uppercase tracking-[0.28em] text-[#5E858C]">
              Source orientation
            </p>
            <p className="absolute bottom-6 left-6 max-w-xs text-sm leading-7 text-[#52686E]">
              Radial sources project broadly toward the scalp. Tangential sources can appear displaced or weak depending on orientation.
            </p>
          </div>

          <div>
            <p className="text-[10px] uppercase tracking-[0.34em] text-[#5E858C]">Physics</p>
            <h2 className="mt-5 font-serif text-5xl leading-tight md:text-7xl">
              A strong source can still be hard to see.
            </h2>
            <p className="mt-7 text-lg font-light leading-9 text-[#52686E]">
              Detection depends on synchronization, depth, skull filtering and dipole orientation. Activity on gyri often projects differently from activity within sulci, so scalp EEG is a shaped view of brain activity rather than a direct image of each source.
            </p>
          </div>
        </div>
      </section>

      <section className="bg-[#061215] px-5 py-20 text-white md:px-10">
        <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.8fr_1.2fr]">
          <div>
            <p className="text-[10px] uppercase tracking-[0.34em] text-[#88B7A5]">Mastery checklist</p>
            <h2 className="mt-5 font-serif text-5xl leading-tight md:text-7xl">Before the next module.</h2>
          </div>
          <div className="grid gap-3 md:grid-cols-2">
            {[
              "EEG reflects postsynaptic potentials more than action potentials.",
              "Synchronized cortical populations are needed for scalp visibility.",
              "Pyramidal neuron alignment enables open-field summation.",
              "Clinical EEG displays negative potentials upward.",
              "Dipole orientation affects what scalp electrodes can detect.",
              "The 10-20 system standardizes scalp electrode placement.",
            ].map((item) => (
              <div key={item} className="border border-white/10 bg-white/[0.035] p-5 text-sm leading-7 text-[#C9D9DD]">
                {item}
              </div>
            ))}
          </div>
        </div>

        <div className="mx-auto mt-16 flex max-w-7xl flex-wrap gap-4 text-[10px] uppercase tracking-[0.24em] text-[#88B7A5]">
          <a href="https://en.wikipedia.org/wiki/Electroencephalography" target="_blank" rel="noreferrer">
            Electroencephalography
          </a>
          <a href="https://en.wikipedia.org/wiki/10%E2%80%9320_system_(EEG)" target="_blank" rel="noreferrer">
            10-20 system
          </a>
        </div>
      </section>
    </main>
  );
}
